src/api.rs
src/main.rs

- Add current time-entry endpoint.
- Save on the precious bandwith and serialization!

Use time_entries/current endpoint for running time-entries

---

src/api.rs
src/credentials.rs
src/main.rs
src/models.rs

This massively simplifies a lot of the code by piggybacking on the fact that we can use unwrap Results if the current method also returns a result. Basically we are using results everywhere and the result (pun intended) is less `match` boilerplate.
I also used a typealias for the result type to prevent writing `Box<dyn std::error::Error>` all the time, which is quite hard on the eyes

⚠️ Simplify code by using Result

---

src/main.rs
src/models.rs

- Run cargo fmt on modified files
- Show fallback description if TE description is empty
- Add helper to get `chrono::Duration` for TimeEntry

🕐️  Show duration of running entry

---

src/arguments.rs
src/main.rs
src/models.rs

Depends on #4
- Add `list` command
- Show time-entries list

Show time entries log

---

Cargo.lock
Cargo.toml
src/api.rs
src/main.rs

Closes #13 
This splits the implementation of the API from its definition. We now have a `V9ApiClient` which implements the `ApiClient` trait. This separation is meant to simplify testing and what-not

🛰️ Move implementation of API to a trait

---

src/arguments.rs
src/commands/cont.rs
src/commands/mod.rs
src/commands/start.rs
src/main.rs
src/models.rs

* Add `start` command. Description is required, billable is optional.
* Stop running entry before continuing in the `continue` command
```
toggl-cli start -d "Description"
```
We've gotta stop the running entry as the API doesn't do it for us.
The code to "get and stop running entry if there is one" would be a good candidate for a common crate later

▶️ Add Start command

---

.github/workflows/pull_request.yml

While testing #26 I noticed that it simply won't build on Windows (😢) and CI didn't catch it because it was running on Ubuntu only.
This mitigates that problem

🖥️ Add all supported platforms to CI

---

Cargo.lock
Cargo.toml
src/arguments.rs
src/commands/auth.rs
src/commands/cont.rs
src/main.rs

- Use `skim` to integrate fzf like interactive selection
-  `skim` seems really unpolished atm, support for generic/custom elements is very rough
- We can't get an index of the selected result back.
- The downcast examples mentioned in https://github.com/lotabout/skim/blob/6df015987934bd63121be53d8659da0f44237dac/src/lib.rs#L90-L100 caused panic on execution for me, if either of you can get it to work, we can skip doing an additional pass on the array to match the TE id.
- Tests, I saw the skim repo for test examples, it's doable but I'm kind of burned out on this particular PR for now, and would prefer doing it as a follow-up.
- See it in action
https://user-images.githubusercontent.com/1716853/123015365-7f718c80-d3c8-11eb-9187-1408f81fdaa5.mov
Closes #10

Add interactive continue

---

src/commands/stop.rs

- Log time-entry when it's stopped, to match start behaviour
Closes #32

🛑 Show time-entry info on stopping

---

Cargo.lock
Cargo.toml
README.md

This renames the binary from `toggl-cli` to `toggl`, since it's obviously a cli app when it's being invoked from the command line

✏️ Rename binary to toggl

---

src/commands/cont.rs
src/commands/start.rs
src/commands/stop.rs
src/main.rs

This is a tiny refactor PR that makes the start and continue commands use the stop command to ensure that there's no running time entry. ATM we are handling time entry stop in three different places and in three different ways. This way things are more concise and DRY

🏗 Reuse StopCommand code for other commands

---

Cargo.lock
Cargo.toml
src/arguments.rs
src/config/active.rs
src/config/fixtures/base.toml
src/config/fixtures/complex.toml
src/config/fixtures/default.toml
src/config/locate.rs
src/config/manage.rs
src/config/mod.rs
src/config/model.rs
src/config/parser.rs
src/constants.rs
src/error.rs
src/main.rs
src/utilities.rs

- 🧠 Add custom deserialization for BranchConfig
- 🕴️ Store branch config as array
- 🌌 Add custom parsing for TrackConfig
- 🏋️‍♂️ Add `toggl config active`
- See config parsing demo.
[![asciicast](https://asciinema.org/a/qQXexPPkAKHXULne9JM1t8on4.svg)](https://asciinema.org/a/qQXexPPkAKHXULne9JM1t8on4)
- Another demo showing the config matching via the `toggl config active` command
[![asciicast](https://asciinema.org/a/r6fBXDNbA0DLEcTMwfaTW8Oai.svg)](https://asciinema.org/a/r6fBXDNbA0DLEcTMwfaTW8Oai)
- Try running `toggl config` for various macros and shell commands.
- Sample complex configuration with a bunch of shell expansions
```toml
['*']
description = "🔨 {{branch}} / {{current_dir}}"
project = "{{parent_base_dir}}"
billable = true
['alt']
description = "chore(release)"
project = …
```

🌌 Resolve tracking config templates

---

src/api/client.rs

- Fetches network entities concurrently.
- Move the await down, so the requests are dispatched in parallel.
- Improves perceived startup performance
- Instead of blocking, all entities are fetched simultaneously

🛹 Fetch entities concurrently

---

src/api/client.rs
src/api/models.rs
src/arguments.rs
src/commands/cont.rs
src/commands/start.rs
src/main.rs
src/models.rs
src/picker/fzf.rs
src/picker/mod.rs
src/picker/skim.rs

Closes #47
This changes the API so that:
- `--fzf` is now globally configurable
- The prompts will only ever appear in `toggl start` if you are passing `-i`
- Interactive mode will only prompt field you haven't explicitly passed to the command line (if you pass `--description foo` it will just use that instead of asking for a description)
- All default values come from the plain default time entry, but in the future they will be configurable, courtesy of #45

🧠 Interactive time entry start

---

src/commands/start.rs
src/config/active.rs
src/config/model.rs
src/models.rs

- 📦 Add `get_active_config` to TrackConfig
- 🌟 Prefill time-entry using active config
- This PR implements part 3 of the spec described in #45.
- We use the active configuration implemented in #53 as defaults for
our time-entry.
- Not sure if we should do the following in this PR or as a follow-up.
- Create missing entities (projects and tasks) if they don't exist.
- Fetch workspaces as part of `Entities` and implement default matching
for configuration.
```console
$ toggl config active
$ toggl start
$ toggl start --interactive
```
https://github.com/watercooler-labs/toggl-cli/assets/1716853/d6772c86-0c4d-4128-9564-1fd96a22a7cb
See #45 for the configuration proposal.

Integrate configuration into tracking

---

src/utilities.rs

- Adds a check using `std::io::stdout().is_terminal()` to decide
if we should log the simplified or the full path.
```console
$ toggl config --path # logs the simplified path
$ cat "$(toggl config --path)" # correctly logs the config toml
```
```console
$ toggl config init
$ toggl config --delete
$ toggl config --path
```
Closes #63

🩹 Fix path output when stdout is not terminal

---

src/commands/list.rs

Piping the output of `toggl list` would panic, probably because of calling println! in a loop, which we should not do:
https://rust-cli.github.io/book/tutorial/output.html#a-note-on-printing-performance
I updated the list command code to use a BufWriter and `writeln!`. I used `expect` to deal with writeln errors. I think we could have an error type in the future that absorbs `io::Error`, what do you think?
Anyway, with this the list command stopped panicking when piping.

fix: use BufWriter in list command to avoid println! in a loop

---

src/config/model.rs

When inside a Git worktree, the path to root can be relative, e.g., ../.git/modules/foo. When this happens, the attempt to get the root's parent's parent's parent fails to unwrap at config/model.rs:389, causing a panic. If we canonicalize the path first, this doesn't happen.

Canonicalize path of Git root.

---

Cargo.lock
Cargo.toml
src/commands/list.rs
src/credentials.rs

- 🎩 Report underlying error when credential write or delete fails
- 🔑 Enable `linux-default-keyutils` feature for keyring
- `keyring` falls back to `keyutils` if `secure-storage` is not available
- Closes #72

Fix linux keyring failure

---

src/api/client.rs
src/api/models.rs
src/commands/start.rs
src/config/model.rs
src/constants.rs
src/error.rs
src/models.rs

- 📥 Use workspace specified in config
If workspace name is specified in the config, we use it while creating a new time-entry.
If the workspace name cannot be matched against the fetched workspaces from the API, we raise an error.
If workspace name is not specified in the config, we use the default workspace.
> Note: At the moment I don't have access to multiple workspaces, it's a paid feature.
> So, I'm unable to test this feature comprehensively. I've tested it with the workspace I have access to.
> Both by specifying the workspace name explicitly in the config and by omitting it.
[![asciicast](https://asciinema.org/a/ejJ6Rw0KDnzoj2lBahQwBjdXO.svg)](https://asciinema.org/a/ejJ6Rw0KDnzoj2lBahQwBjdXO)
[![asciicast](https://asciinema.org/a/oKoceoKUIsaYHntcyC6AUDzFf.svg)](https://asciinema.o …

Add support for setting workspace using the config

---

src/commands/auth.rs
src/commands/cont.rs
src/config/model.rs
src/constants.rs
src/credentials.rs
src/error.rs
src/main.rs

- 🌳 Read token from TOGGL_API_TOKEN environment variable
- Environment store overrides keyring store, write and delete operations
are disabled for the keyring store.
- This should allow linux users to authenticate and persist their credentials
in their shell configuration, until we figure out the keyring crate's persistence issue
Closes #81

Support reading token from environment variable

---

src/commands/start.rs
src/config/fixtures/default.toml

- Start command should work even if config doesn't exist
```rust
let config_path = config::locate::locate_config_path()?;
let track_config = config::parser::get_config_from_file(config_path)?;
let default_time_entry = track_config.get_default_entry(entities.clone())?;
```
These established a hard dependency on the `config` infrastructure.
We fix this, by only following the config code branch if a configuration
path can be located.
**Caveat**: This silences the error if a configuration is found but cannot
be parsed. I'm treading on the side of simplicity over correctness here.
In future we might treat the configuration error as a critical error.
- Simplify default config file
Previously our default config for `toggl config --init` enforced
the use of git.
Such that, even for non-vcs …

Fix configuration use in start command

---

src/arguments.rs
src/commands/start.rs
src/main.rs

Add support for `--tags` (short `-t`) to the `toggl start` command.
This accepts a space-separated list of tags to apply to the time entry.
```bash
toggl start 'Add initial database' --tags code dev --project watercooler-labs
```
[![asciicast](https://asciinema.org/a/ESgBGQ5ZMf3yJ4yliB8JIhz6z.svg)](https://asciinema.org/a/ESgBGQ5ZMf3yJ4yliB8JIhz6z)
> **Note**: `--tags` will override any tags configured in the directory configuration.
Closes #83

👾 Allow tags to be set in `start` command
